# Generated by Django 6.0.2 on 2026-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default=None, upload_to='assets/favicon/%Y/%m/%d'),
        ),
    ]
